image:
  file: .gitpod.Dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

vscode:
  extensions:
    - alygin.vscode-tlaplus
    - tintinweb.graphviz-interactive-preview
    - cssho.vscode-svgviewer
    - tomoki1207.pdf